version: 1.0.{build}
os:
  - Visual Studio 2015
clone_depth: 1
environment:
  matrix:
    - TOOLCHAIN_VERSION: 14.0
      RUST: 1.9.0
      PYTHON: "C:\\Python35"
      platform: Win32

    - TOOLCHAIN_VERSION: 14.0
      RUST: beta
      PYTHON: "C:\\Python35"
      platform: Win32

    - TOOLCHAIN_VERSION: 14.0
      RUST: nightly
      PYTHON: "C:\\Python35"
      platform: Win32

    - TOOLCHAIN_VERSION: 14.0
      RUST: 1.9.0
      PYTHON: "C:\\Python35-x64"
      platform: x64

    - TOOLCHAIN_VERSION: 14.0
      RUST: beta
      PYTHON: "C:\\Python35-x64"
      platform: x64

    - TOOLCHAIN_VERSION: 14.0
      RUST: nightly
      PYTHON: "C:\\Python35-x64"
      platform: x64

    - TOOLCHAIN_VERSION: 14.0
      RUST: 1.9.0
      PYTHON: "C:\\Python34"
      DISTUTILS_USE_SDK: "1"
      platform: Win32

    - TOOLCHAIN_VERSION: 14.0
      RUST: beta
      PYTHON: "C:\\Python34"
      DISTUTILS_USE_SDK: "1"
      platform: Win32

    - TOOLCHAIN_VERSION: 14.0
      RUST: nightly
      PYTHON: "C:\\Python34"
      DISTUTILS_USE_SDK: "1"
      platform: Win32

    - TOOLCHAIN_VERSION: 14.0
      RUST: 1.9.0
      PYTHON: "C:\\Python34-x64"
      DISTUTILS_USE_SDK: "1"
      platform: x64

    - TOOLCHAIN_VERSION: 14.0
      RUST: beta
      PYTHON: "C:\\Python34-x64"
      DISTUTILS_USE_SDK: "1"
      platform: x64

    - TOOLCHAIN_VERSION: 14.0
      RUST: nightly
      PYTHON: "C:\\Python34-x64"
      DISTUTILS_USE_SDK: "1"
      platform: x64

    - TOOLCHAIN_VERSION: 14.0
      RUST: 1.9.0
      PYTHON: "C:\\Python33"
      DISTUTILS_USE_SDK: "1"
      platform: Win32

    - TOOLCHAIN_VERSION: 14.0
      RUST: beta
      PYTHON: "C:\\Python33"
      DISTUTILS_USE_SDK: "1"
      platform: Win32

    - TOOLCHAIN_VERSION: 14.0
      RUST: nightly
      PYTHON: "C:\\Python33"
      DISTUTILS_USE_SDK: "1"
      platform: Win32

    - TOOLCHAIN_VERSION: 14.0
      RUST: 1.9.0
      PYTHON: "C:\\Python33-x64"
      DISTUTILS_USE_SDK: "1"
      platform: x64

    - TOOLCHAIN_VERSION: 14.0
      RUST: beta
      PYTHON: "C:\\Python33-x64"
      DISTUTILS_USE_SDK: "1"
      platform: x64

    - TOOLCHAIN_VERSION: 14.0
      RUST: nightly
      PYTHON: "C:\\Python33-x64"
      DISTUTILS_USE_SDK: "1"
      platform: x64

    - TOOLCHAIN_VERSION: 14.0
      RUST: 1.9.0
      PYTHON: "C:\\Python27"
      platform: Win32

    - TOOLCHAIN_VERSION: 14.0
      RUST: beta
      PYTHON: "C:\\Python27"
      platform: Win32

    - TOOLCHAIN_VERSION: 14.0
      RUST: nightly
      PYTHON: "C:\\Python27"
      platform: Win32

    - TOOLCHAIN_VERSION: 14.0
      RUST: 1.9.0
      PYTHON: "C:\\Python27-x64"
      platform: x64

    - TOOLCHAIN_VERSION: 14.0
      RUST: beta
      PYTHON: "C:\\Python27-x64"
      platform: x64

    - TOOLCHAIN_VERSION: 14.0
      RUST: nightly
      PYTHON: "C:\\Python27-x64"
      platform: x64

matrix:
  allow_failures:
    - RUST: nightly

install:
  - "git submodule update --init --recursive"

build_script: appveyor/build.bat

after_test:
  - "appveyor\build.cmd %PYTHON%\\python.exe setup.py bdist_wheel"

artifacts:
  - path: dist\*