version: 1.0.{build}
os:
  - Visual Studio 2015
clone_depth: 1
environment:
  matrix:
    - TOOLCHAIN_VERSION: 14.0
      RUST: 1.5.0
      PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5.0"
      PYTHON_ARCH: "32"
      platform: Win32

    - TOOLCHAIN_VERSION: 14.0
      RUST: beta
      PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5.0"
      PYTHON_ARCH: "32"
      platform: Win32

    - TOOLCHAIN_VERSION: 14.0
      RUST: nightly
      PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5.0"
      PYTHON_ARCH: "32"
      platform: Win32

    - TOOLCHAIN_VERSION: 14.0
      RUST: 1.5.0
      PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5.0"
      PYTHON_ARCH: "64"
      platform: x64

    - TOOLCHAIN_VERSION: 14.0
      RUST: beta
      PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5.0"
      PYTHON_ARCH: "64"
      platform: x64

    - TOOLCHAIN_VERSION: 14.0
      RUST: nightly
      PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5.0"
      PYTHON_ARCH: "64"
      platform: x64

matrix:
  allow_failures:
    - RUST: nightly

install:
  # Install Python (from the official .msi of http://python.org) and pip when
  # not already installed.
  - "powershell ./appveyor/install.ps1"
  - "git submodule update --init --recursive"

build_script: appveyor/build.bat